### ISSUE TITLE
Would you let me know the way how I attach dia2scala.jar to dia?

### ISSUE THREAD

**Issue by mcdoyaji** [mnn/Dia2Scala#1]
I am ubuntu 15.10 64bit user.

I already installed dia and did "sbt compile" this Dia2Scala source.

What's next step to use Dia2Scala?

**Comment by mnn** [comment]
Run `sbt assembly` and then a JAR file should be located at the `target` directory ;-).

**Comment by dbYoung** [comment]
@mnn Thank you :+1:

**Comment by mcdoyaji** [comment]
Thanks @mnn !! What's the next step?

Where do I put the JAR file into??

**Comment by mnn** [comment]
You should be able to run it now, usually something like `java -jar dia2scala_0.1.jar --help`.

**Comment by mcdoyaji** [comment]
Thanks @mnn  !! Now I see the options.
